ESX = nil                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)                                                                                            

RegisterNetEvent('lunapark:onRide')
AddEventHandler('lunapark:onRide', function(player)
    TriggerClientEvent('lunapark:syncPlayer', xPlayer.source)
end)

RegisterNetEvent('lunapark:loadOtherPlayerAnim') 
AddEventHandler('lunapark:loadOtherPlayerAnim', function(otherPlayer)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
    TriggerClientEvent('lunapark:loadPedAnimTimed', -1, otherPlayer)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
end)
